# Generated by Django 5.2.2 on 2025-12-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='session_key',
            field=models.CharField(blank=True, help_text='Гостевая корзина (по сессии)', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
